changelog:
  exclude:
    labels:
      - ignore-changelog
    authors:
      - github-actions[bot]
  categories:
    - title: "Model architecture & tuning"
      labels:
        - model
        - enhancement
    - title: "Feature engineering"
      labels:
        - features
        - data
    - title: "Other changes"
      collapse_after: 3