# Work on dev branch -> PR (tests) -> Merge to main -> Submit submission.csv 
name: Submit to Kaggle

# Event trigger for the workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

# List of jobs to run
jobs:
  submit_predictions:
    name: Submit predictions
    runs-on: ubuntu-latest

  # Sequence of steps to submit predictions
  steps:

    # Checkout code from the repo
    - name: Checkout
      uses: actions/checkout@v7.0.0

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v6.3.0
      with:
        python-version: "3.12"

    # Install Kaggle CLI
    - name: Install Kaggle CLI
      run: pip install --no-cache-dir kaggle

    # Authenticate Kaggle CLI
    - name: Authenticate Kaggle CLI
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}

    # Submit predictions CSV
    - name: Submit to competition
      run: kaggle competitions submit -c playground-series-s6e7 -f ../data/submission.csv -m "Submission from GitHub Actions"